### ISSUE TITLE
There should be support for "normal" fontStyle

### ISSUE THREAD

**Issue by chuckfossen** [FichteFoll/CSScheme#14]
When I convert from tmTheme file to csscheme, 

```
<key>fontStyle</key>
<string>normal</string>
```

is converted to 
    fontStyle: normal;

But when converting from csscheme to tmTheme, I get an error:
  invalid value 'normal' for style property fontStyle in "keyword.operator"

**Comment by FichteFoll** [comment]
`fontStyle: none;` is most definitely what you want.
