### ISSUE TITLE
Allow generation of hidden-tmTheme

### ISSUE THREAD

**Issue by pradyunsg** [FichteFoll/CSScheme#9]
Possibly with a `@hidden: true` key in the "global/top-level" along with name?

**Comment by FichteFoll** [comment]
Good point, will look into it.

**Comment by pradyunsg** [comment]
Thanks!

PS: Not that I intend to be picky, but the commit message is wrong. :sweat_smile:

**Comment by pradyunsg** [comment]
Also, this has not been included in the README.

**Comment by FichteFoll** [comment]
> this has not been included in the README.

It has been: a37a2078156a26eccaaedbb3acb64ee9b4a1e6f0.

>but the commit message is wrong

whoops

**Comment by pradyunsg** [comment]
Yay! It works awesome!! :smile: Thanks!
